services:
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    ports:
      - "9080:9080"
    restart: unless-stopped
    volumes:
      - /home/MineGod/mineworld/logs:/var/log/minecraft
      - ./promtail.yaml:/etc/promtail/config.yml
    command: ["-config.expand-env=true" ,"-config.file=/etc/promtail/config.yml"]
    privileged: true

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yml
    command: ["-config.file=/etc/loki/local-config.yml"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    #PASSWORD NEW: Ayetatary228!
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasourses.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./grafana.ini:/etc/grafana/grafana.ini
      - grafanadata:/var/lib/grafana



volumes:
  grafanadata:
  prometheusdata: