global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'minecraft'
    metrics_path: /metrics
    static_configs:
      - targets: ['77.232.132.16:9940']
        labels:
          server_name: 'minecraftorgcom.ru'
